<?php

/**
 * ProTalk
 *
 * Copyright (c) 2012-2013, ProTalk
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Protalk\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends EntityRepository
{
    /**
     * Get all speakers and count of their entries
     *
     * @return Doctrine Collection
     */
    public function getAllSpeakers()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('s.slug', 's.name', 'COUNT(m.id) as mediaCount');
        $qb->from('\Protalk\MediaBundle\Entity\Speaker', 's');
        $qb->join('s.medias', 'ms');
        $qb->join('ms.media', 'm');
        $qb->where('m.status = :status');
        $qb->groupBy('s.name');
        $qb->orderBy('s.name', 'ASC');

        $query = $qb->getQuery();
        $query->setParameter("status", Media::STATUS_PUBLISHED);

        return $query->execute();
    }

    /**
     * Gets speakers with filters / options [api]
     */
    public function getSpeakers($count, $hydrator = Query::HYDRATE_SINGLE_SCALAR)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('s.id', 's.name', 'COUNT(m.id) as mediaCount');
        $qb->from('\Protalk\MediaBundle\Entity\Speaker', 's');
        $qb->join('s.medias', 'ms');
        $qb->join('ms.media', 'm');
        $qb->where('m.status = :status');
        $qb->groupBy('s.name');
        $qb->orderBy('s.name', 'ASC');
        $qb->setMaxResults($count);

        $query = $qb->getQuery();
        $query->setParameter("status", Media::STATUS_PUBLISHED);

        return $query->getArrayResult($hydrator);
    }

    public function findOneById($id, $hydrator = Query::HYDRATE_SINGLE_SCALAR)
    {
        $query = $this->createQueryBuilder('s')
            ->where('s.id = :id')
            ->setParameter('id', $id);

        return $query->getQuery($hydrator)->getOneOrNullResult($hydrator);
    }
}
