language: php
php:
  - "5.4"
  - "5.3"

before_script:
  - cp app/config/parameters.yml-dist app/config/parameters.yml
  - composer install
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script: phpunit -c app/ --coverage-text

after_script:
  - phpcs --report=full --report=gitblame --standard=PSR2 src/

notifications:
  irc:
    - "irc.freenode.org#protalk"
